# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9692a0b82af33ed2541a744eae67b2599f5ade480e2e3937eb7ab4ad55b222f94b1a70c5d0fca4c44625696b1dc2e00f7135d196adae719098409b378e63f44

test:
  secret_key_base: 573e07b2c294b447aa4d7f79e5d30fd086b0161cdc7ceee54352ec3acc6970222b4b412903d1ff4cb0f112e22f034f5ca3f1c4dd1d7e3036c39b747591eb1a62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
